# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 03:35
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def load_initial_data(app, schema_editor):
    """
    Creates the initial superadmin user for acm@mst.edu.
    """
    User = app.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    admin = User.objects.create(
        email="acm@mst.edu", is_staff=True, is_superuser=True,
        first_name="ACM", last_name="MST",
        password=make_password(None)
    )
    admin.save()


def reverse_initial_data(apps, schema_editor):
    """
    Reverts the creation of the initial superadmin user.
    """
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(email="acm@mst.edu").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_initial_data)
    ]
