# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sigs.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.CharField(default='test', help_text='The UUID of the Special Interest Group.', max_length=25, primary_key=True, serialize=False, verbose_name='SIG ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether or not the SIG is active', verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the SIG was created.', verbose_name='Date Created')),
                ('description', models.CharField(help_text='A description of what the special interest of the group is.', max_length=1000, verbose_name='Description')),
                ('chair', models.ForeignKey(help_text='The current Chair of the SIG.', on_delete=django.db.models.deletion.PROTECT, related_name='chair', to=settings.AUTH_USER_MODEL, verbose_name='SIG Chair')),
                ('founder', models.ForeignKey(help_text='The person who founded the SIG.', on_delete=django.db.models.deletion.PROTECT, related_name='founder', to=settings.AUTH_USER_MODEL, verbose_name='SIG Founder')),
            ],
            managers=[
                ('objects', sigs.managers.SIGManager()),
            ],
        ),
    ]
