# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sigs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('tag', models.CharField(primary_key=True, verbose_name='Product Tag', help_text='Unique human-readable product identifier', max_length=50)),
                ('name', models.CharField(help_text='The name of the Product', max_length=50, verbose_name='Product Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date in which the transaction was created', verbose_name='Date Created')),
                ('cost', models.DecimalField(decimal_places=2, help_text='How much the transaction costed.', max_digits=7, verbose_name='Transaction Cost')),
                ('description', models.CharField(help_text='A description of the transaction.', max_length=500, verbose_name='Transaction Description')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date in which the transaction was created.', verbose_name='Date Created')),
                ('description', models.CharField(help_text='A description of the transaction.', max_length=500, verbose_name='Transaction Description')),
                ('cost', models.DecimalField(decimal_places=2, help_text='How much the transaction costed.', max_digits=7, verbose_name='Transaction Cost')),
                ('charge_id', models.CharField(help_text='The identifier associated with the stripe charge.', max_length=50, verbose_name='Stripe Charge ID')),
                ('stripe_token', models.CharField(help_text='The token associated with the stripe payment.', max_length=50, verbose_name='Transaction Stripe Token')),
                ('customer_id', models.CharField(help_text='The Customer ID associated with the user.', max_length=50, verbose_name='Transaction Customer ID')),
                ('coupon_id', models.CharField(blank=True, help_text='The coupon which the user used in the transaction.', max_length=50, null=True, verbose_name='Transaction Stripe Token')),
                ('subscription_id', models.CharField(blank=True, help_text='The subscription id associated with the charge.', max_length=50, null=True, verbose_name='Transaction Subscription ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the Category', max_length=50, verbose_name='Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.TransactionCategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sigs.SIG'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='The user which completed the transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Transaction User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='The category of the type of transaction.', on_delete=django.db.models.deletion.PROTECT, to='products.TransactionCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='sig',
            field=models.ForeignKey(help_text='The SIG to whom the Product is related to.', on_delete=django.db.models.deletion.PROTECT, to='sigs.SIG'),
        ),
    ]
