# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 03:35
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def load_initial_data(app, schema_editor):
    """
    Creates the initial superadmin user for acm@mst.edu.
    """
    SIG = app.get_model("sigs", "SIG")
    TransactionCategory = app.get_model("products", "TransactionCategory")
    Product = app.get_model("products", "Product")

    db_alias = schema_editor.connection.alias

    acm_general = SIG.objects.get(id="acm-general")
    acm_memberships = TransactionCategory.objects.create(name="acm-memberships")
    acm_memberships.save()

    membership_semester = Product.objects.create(
        name="ACM Semester Membership",tag="membership-semester",
        cost=11.00, description="ACM Semesterly Membership",
        category=acm_memberships, sig=acm_general
    )
    membership_semester.save()

    membership_year = Product.objects.create(
        name="ACM Year Membership", tag="membership-year",
        cost=20.00, description="ACM Yearly Membership",
        category=acm_memberships, sig=acm_general
    )
    membership_year.save()




def reverse_initial_data(apps, schema_editor):
    """
    Reverts the creation of the initial superadmin user.
    """
    User = apps.get_model("sigs", "SIG")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(id="acm-general").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0002_starting_data'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_initial_data)
    ]
