# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='ACM User ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='When the event was created.', verbose_name='Date Created')),
                ('date_hosted', models.DateTimeField(help_text='When the event will be held.', verbose_name='Date Hosted')),
                ('date_expire', models.DateTimeField(help_text='When the event is over.', verbose_name='Expire Date')),
                ('title', models.CharField(help_text='A human-readable title of the event.', max_length=256, verbose_name='Event Title')),
                ('description', models.CharField(help_text='A description of what the event will consist of.', max_length=1000, verbose_name='Event Description')),
                ('location', models.CharField(help_text='Where the event is being hosted.', max_length=256, verbose_name='Event Location')),
                ('presenter', models.CharField(blank=True, help_text='Who is presenting at the event.', max_length=256, verbose_name='Event Presenter')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='How much the event costs to participate.', max_digits=6, verbose_name='Event Cost')),
                ('flier', models.ImageField(help_text='The image for the flier.', upload_to=events.models.get_path_for_flier, verbose_name='Flier Image')),
                ('link', models.URLField(blank=True, help_text='An optional link for the event.', verbose_name='Event Link')),
                ('creator', models.ForeignKey(help_text='The user who created the event.', on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('hosting_sig', models.ForeignKey(help_text='The SIG hosting the event.', on_delete=django.db.models.deletion.CASCADE, related_name='SIG', to='sigs.SIG', verbose_name='Hosting SIG')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together=set([('event_id', 'user_id')]),
        ),
    ]
