# Generated by Django 2.0.3 on 2018-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('display_name', models.CharField(help_text='The name of the tag that will be displayed to users.', max_length=256, unique=True, verbose_name='Event Tag')),
                ('id', models.CharField(help_text='Unique ID of the tag.', max_length=256, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=True, help_text='Whether or not the tag is to be displayed.', verbose_name='Display')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text='The name of the Tag that will be displayed to users', to='events.Tag', verbose_name='Event Tags'),
        ),
    ]
