# Generated by Django 2.0.3 on 2018-04-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180330_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The name of the Tag that will be displayed to users', to='events.Tag', verbose_name='Event Tags'),
        ),
    ]
